#!/usr/bin/env bash
set -euo pipefail

root_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

update=0
if [[ "${1:-}" == "--update" ]]; then
  update=1
  shift
fi

cd "$root_dir"

make -s decoder enc_pngdump enc_m04_miniframe

expected_file="scripts/enc_m04_miniframe_expected.txt"
tmp_file="build/enc_m04_miniframe_manifest.tmp"

# Keep this list small and stable.
declare -a cases=(
  "1 1"
  "16 16"
  "17 17"
  "31 9"
  "64 33"
)

rm -f "$tmp_file"

for c in "${cases[@]}"; do
  read -r w h <<<"$c"
  out_webp="build/enc_m04_${w}x${h}.webp"
  out_png="build/enc_m04_${w}x${h}.png"
  out_rgb="build/enc_m04_${w}x${h}.rgb"

  rm -f "$out_webp" "$out_png" "$out_rgb"

  ./build/enc_m04_miniframe "$w" "$h" "$out_webp"

  # Must decode (macroblocks/tokens).
  ./decoder -probe "$out_webp" >/dev/null

  # Decode to PNG, reparse PNG, hash raw RGB.
  ./decoder -png "$out_webp" "$out_png"
  ./build/enc_pngdump "$out_png" > "$out_rgb"

  want_bytes=$((w*h*3))
  got_bytes="$(wc -c < "$out_rgb" | tr -d ' ')"
  if [[ "$got_bytes" != "$want_bytes" ]]; then
    echo "FAIL: $w x $h: unexpected RGB byte count: got $got_bytes want $want_bytes" >&2
    exit 1
  fi

  sha="$(sha256sum "$out_rgb" | awk '{print $1}')"
  printf '%sx%s  %s\n' "$w" "$h" "$sha" >> "$tmp_file"
done

LC_ALL=C sort -o "$tmp_file" "$tmp_file"

if [[ $update -eq 1 ]]; then
  {
    echo "# Generated by scripts/enc_m04_miniframe_check.sh --update"
    echo "# Format:"
    echo "#   <width>x<height>  <sha256 of raw RGB bytes>"
    cat "$tmp_file"
  } > "$expected_file"
  echo "UPDATED: $expected_file" >&2
  exit 0
fi

if [[ ! -f "$expected_file" ]]; then
  echo "FAIL: missing $expected_file (run with --update once)" >&2
  exit 1
fi

# Compare only the data lines (ignore comments).
grep -v '^#' "$expected_file" | sed '/^$/d' > "${tmp_file}.expected"
diff -u "${tmp_file}.expected" "$tmp_file"

echo "OK: enc m04 miniframe cases decode and hashes match" >&2
