#include <math.h>
#include <stdint.h>
#include <stdio.h>

enum {
	GAMMA_FIX = 12,
	GAMMA_TAB_FIX = 7,
	GAMMA_TAB_SIZE = 1 << (GAMMA_FIX - GAMMA_TAB_FIX),
};

static void gen_gamma_tables(void) {
	const double kGamma = 0.80;
	const int kGammaScale = (1 << GAMMA_FIX) - 1;
	const int kGammaTabScale = 1 << GAMMA_TAB_FIX;
	(void)kGammaTabScale;

	uint16_t gamma_to_linear[256];
	int linear_to_gamma[GAMMA_TAB_SIZE + 1];

	const double norm = 1.0 / 255.0;
	const double scale = (double)(1 << GAMMA_TAB_FIX) / (double)kGammaScale;
	for (int v = 0; v <= 255; v++) {
		gamma_to_linear[v] =
			(uint16_t)(pow(norm * (double)v, kGamma) * (double)kGammaScale + 0.5);
	}
	for (int v = 0; v <= GAMMA_TAB_SIZE; v++) {
		linear_to_gamma[v] =
			(int)(255.0 * pow(scale * (double)v, 1.0 / kGamma) + 0.5);
	}

	printf("// Generated by tools/gen_enc_tables.c\n");
	printf("// Gamma=%0.2f, GAMMA_FIX=%d, GAMMA_TAB_FIX=%d\n\n", kGamma, GAMMA_FIX, GAMMA_TAB_FIX);

	printf("#include <stdint.h>\n\n");
	printf("const uint16_t enc_gamma_to_linear_tab[256] = {\n");
	for (int i = 0; i < 256; i++) {
		printf("%s%u", (i % 12 == 0) ? "\t" : " ", (unsigned)gamma_to_linear[i]);
		printf("%s", (i == 255) ? "" : ",");
		if (i % 12 == 11 || i == 255) printf("\n");
	}
	printf("};\n\n");

	printf("const int enc_linear_to_gamma_tab[%d] = {\n", GAMMA_TAB_SIZE + 1);
	for (int i = 0; i < GAMMA_TAB_SIZE + 1; i++) {
		printf("%s%d", (i % 12 == 0) ? "\t" : " ", linear_to_gamma[i]);
		printf("%s", (i == GAMMA_TAB_SIZE) ? "" : ",");
		if (i % 12 == 11 || i == GAMMA_TAB_SIZE) printf("\n");
	}
	printf("};\n");
}

static int clamp_i32(int v, int lo, int hi) {
	if (v < lo) return lo;
	if (v > hi) return hi;
	return v;
}

static void gen_quality_table(void) {
	uint8_t qindex[101];
	for (int quality = 0; quality <= 100; quality++) {
		const double q01 = (double)quality / 100.0;
		const double linear_c = (q01 < 0.75) ? q01 * (2. / 3.) : 2. * q01 - 1.;
		const double c = pow(linear_c, 1.0 / 3.0);
		const int qi = clamp_i32((int)(127.0 * (1.0 - c)), 0, 127);
		qindex[quality] = (uint8_t)qi;
	}

	printf("\n// Generated by tools/gen_enc_tables.c\n\n");
	printf("#include <stdint.h>\n\n");
	printf("const uint8_t enc_qindex_from_quality[101] = {\n");
	for (int i = 0; i <= 100; i++) {
		printf("%s%u", (i % 16 == 0) ? "\t" : " ", (unsigned)qindex[i]);
		printf("%s", (i == 100) ? "" : ",");
		if (i % 16 == 15 || i == 100) printf("\n");
	}
	printf("};\n");
}

int main(void) {
	gen_gamma_tables();
	gen_quality_table();
	return 0;
}
